/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Allora' at '17/07/13 16:33' with Gradle 3.2.1
 *
 * @author Allora, @date 17/07/13 16:33
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
